completed splash screen
BakriIWNL/internship_implementation pull request #1
Opened 2024-11-25 15:04 UTC by BakriIWNL

currently working on onboarding

2024-11-27 09:04 UTC, YousefSalahKassem requested changes
GOOD JOB !
but need to focus on this comments

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/cubit/carousel/carousel_state.dart
> +class CarouselState {
good job but need from u to search about equtable because you will need it

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/splashscreen.dart
> +  void initState() {
don't use statefull use stateless and make cubit for splash to add your logic for start app

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/splashscreen.dart
> +            'montra',
localized it

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/splashscreen.dart
> +            style: GoogleFonts.inter(
never use this package 
NEVER!

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboardingscreen.dart
> +                    "Log in",
localized it please

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboardingscreen.dart
> +                    fixedSize: (Size(MediaQuery.of(context).size.width * 0.915, 56.h)),
huh ?
why ?

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboardingscreen.dart
> +  State<OnboardingScreen> createState() => _OnboardingScreenState();
don't use statefull widget

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboardingscreen.dart
> +                Carousel(),
make it meaningfull name please

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboardingscreen.dart
> +                      borderRadius: BorderRadius.circular(16.0.r),
don't need for decimal

2024-11-27 09:04 UTC, YousefSalahKassem commented on pubspec.yaml
> +  google_fonts: ^6.2.1
don't use this package google_fonts 
NEVER

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/core/utils/onboardinginfo.dart
> +class OnBoardingInfo {
this model related to onboarding so move it to onboarding feature 
for example: 
onboarding/data/models/on_boarding_info.dart
then add this class this path

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/core/utils/routes.dart
> +        path: '/onboarding',
make class to add path names and don't add static names like that 
and make folders for routes inside core/routes 

and make class for route_names.dart
and routes class which is this one

2024-11-27 09:04 UTC, YousefSalahKassem commented on lib/core/utils/app_assets.dart
> +class AppAssets {
better to make folder for themes and add assets and colors in themes folder inside core 
core/themes/..

2024-11-27 09:26 UTC, BakriIWNL commented on lib/features/onboarding/presentation/screens/splashscreen.dart
> +            style: GoogleFonts.inter(
removed

2024-11-27 09:26 UTC, BakriIWNL commented on lib/features/onboarding/presentation/screens/splashscreen.dart
> +            'montra',
done

2024-11-28 13:32 UTC, BakriIWNL commented on lib/features/onboarding/presentation/screens/splashscreen.dart
> +  void initState() {
took a bit bs i made it work!

2024-12-01 08:03 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/cubit/splash_screen/splash_screen_state.dart
> +  static SplashScreenState active() {
good job can you also search about factory methods ?

2024-12-01 08:04 UTC, BakriIWNL commented on lib/features/onboarding/presentation/cubit/splash_screen/splash_screen_state.dart
> +  static SplashScreenState active() {
okay

2024-12-01 08:09 UTC, YousefSalahKassem requested changes
good job bak bak

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboarding_screen.dart
> +                        (Size(MediaQuery.of(context).size.width * 0.915, 56.h)),
change this please

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/splash_screen.dart
> +          context.go('/onboarding');
static routes use approutes instead

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/signup/presentation/screens/signup_screen.dart
> +                  hint: 'Password',
can you search about naming constructor 
as you can use CustomTextField and CustomTextField.password()

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/signup/presentation/screens/signup_screen.dart
> +  TextEditingController passwordController = TextEditingController();
dont depend on statefull widget and use stateless widget and make cubit for register to add funs for register with all text controllers, validators and form

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/signup/presentation/screens/signup_screen.dart
> +                  hint: 'Name',
please use localization

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/widgets/onboarding_carousel_slider.dart
> +class OnboardingCarousel extends StatefulWidget {
remove statefull

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboarding_screen.dart
> +                        (Size(MediaQuery.of(context).size.width * 0.915, 56.h)),
also this

2024-12-01 08:09 UTC, YousefSalahKassem commented on lib/features/onboarding/presentation/screens/onboarding_screen.dart
> +                    context.go('/signup');
use app routes

2024-12-01 08:09 UTC, BakriIWNL commented on lib/features/onboarding/presentation/screens/onboarding_screen.dart
> +                        (Size(MediaQuery.of(context).size.width * 0.915, 56.h)),
forgot

2024-12-01 08:10 UTC, BakriIWNL commented on lib/features/onboarding/presentation/screens/splash_screen.dart
> +          context.go('/onboarding');
correct, forgot

2024-12-01 08:10 UTC, BakriIWNL commented on lib/features/signup/presentation/screens/signup_screen.dart
> +  TextEditingController passwordController = TextEditingController();
yes yes, still work in progress

2024-12-01 10:10 UTC, BakriIWNL commented on lib/features/onboarding/presentation/cubit/splash_screen/splash_screen_state.dart
> +  static SplashScreenState active() {
done

2024-12-02 08:42 UTC, YousefSalahKassem commented
LGTM

2024-12-02 08:42 UTC, merged