Signup
BakriIWNL/internship_implementation pull request #3
Opened 2024-12-02 11:44 UTC by BakriIWNL

2024-12-02 12:03 UTC, YousefSalahKassem requested changes
GJ BAK BAK
Please review this comments !

2024-12-02 12:03 UTC, YousefSalahKassem commented on lib/core/components/customtextfield.dart
> +        obscureText: (context.read<SignupCubit>().passwordVisible || !password) ? false : true,
if we have sign in and forget password you will add condition on it ?
don't make any dependency

2024-12-02 12:03 UTC, YousefSalahKassem commented on lib/core/components/light_purple_button.dart
> +
you can make custom button and send color if u have 10 colors you will make buttons for each color ?

2024-12-02 12:03 UTC, YousefSalahKassem commented on lib/core/routes/routes.dart
> +              BlocProvider(
it's single bloc why you need to use multi bloc ?

2024-12-02 12:03 UTC, YousefSalahKassem commented on lib/core/utils/app_strings.dart
> +  static const String email = "Email";
can you implement localization ?

2024-12-02 12:03 UTC, YousefSalahKassem commented on lib/features/signup/presentation/cubits/signup/signup_cubit.dart
> +    emit(state.copyWith(state: GenericStates.updateUI));
imagine u will click on toggle check box and also u found password field is toggled too.
because you emit the same state

2024-12-02 12:03 UTC, YousefSalahKassem commented on lib/features/signup/presentation/screens/signup_screen.dart
> +        child: Form(
for advice separate your code to widgets as u can make private widget for form and private widgets for actions and add all this in signup screen

2024-12-02 12:03 UTC, YousefSalahKassem commented on lib/features/signup/presentation/widgets/checkbox.dart
> +class CheckBox extends StatelessWidget {
make custom component for checkbox only and don't make it depend on feature 
it's just a shareable component

2024-12-02 12:26 UTC, BakriIWNL commented on lib/core/utils/app_strings.dart
> +  static const String email = "Email";
inshallah

2024-12-02 12:37 UTC, BakriIWNL commented on lib/core/components/customtextfield.dart
> +        obscureText: (context.read<SignupCubit>().passwordVisible || !password) ? false : true,
done

2024-12-02 12:41 UTC, BakriIWNL commented on lib/core/components/light_purple_button.dart
> +
done

2024-12-02 12:43 UTC, BakriIWNL commented on lib/core/routes/routes.dart
> +              BlocProvider(
done

2024-12-02 12:44 UTC, BakriIWNL commented on lib/features/signup/presentation/screens/signup_screen.dart
> +        child: Form(
done

2024-12-03 07:36 UTC, YousefSalahKassem requested changes

2024-12-03 07:36 UTC, YousefSalahKassem commented on lib/features/login/presentation/screens/login_screen.dart
> +                      style: TextStyle(
just separate form and action for 2 private stateless widget 
_Form
_Actions

2024-12-03 07:36 UTC, YousefSalahKassem commented on lib/core/components/customtextfield.dart
> +        obscureText: (password) ? false : true,
just put password ?

2024-12-03 08:17 UTC, BakriIWNL commented on lib/core/components/customtextfield.dart
> +        obscureText: (password) ? false : true,
fair enough

2024-12-03 08:24 UTC, BakriIWNL commented on lib/features/login/presentation/screens/login_screen.dart
> +                      style: TextStyle(
done

2024-12-03 09:38 UTC, merged