Setup pin pages
BakriIWNL/internship_implementation pull request #6
Opened 2024-12-03 14:54 UTC by BakriIWNL

2024-12-04 07:50 UTC, YousefSalahKassem requested changes

2024-12-04 07:50 UTC, YousefSalahKassem commented on lib/features/signup/presentation/screens/enter_pin_screen.dart
> +            (MediaQuery.of(context).size.height * 0.45).verticalSpace,
why ?

2024-12-04 07:50 UTC, YousefSalahKassem commented on lib/features/signup/presentation/widgets/pin_numpad.dart
> +            if (index == 9) {
huh ?

2024-12-04 07:50 UTC, YousefSalahKassem commented on lib/features/signup/presentation/cubits/signup/signup_cubit.dart
>    @override
based on solid principles specially S word for single responsibility don't mix between pin screen and signup specially you use signup cubit in pin screen each one should depend on itself

2024-12-05 06:49 UTC, YousefSalahKassem requested changes
GJ 
Please check this comments

2024-12-05 06:49 UTC, YousefSalahKassem commented on lib/core/components/bottomsheets/default_bottomsheet.dart
> +
make custom bottom sheet

2024-12-05 06:49 UTC, YousefSalahKassem commented on lib/core/components/bottomsheets/default_bottomsheet.dart
> +      const DropdownMenuItem(value: '0', child: Text("Bank")),
localize it please

2024-12-05 06:49 UTC, YousefSalahKassem commented on lib/core/components/sheet_screen.dart
> +                10.verticalSpace,
why you add this screen in component ?

2024-12-05 06:49 UTC, YousefSalahKassem commented on lib/features/setup/presentation/widgets/custom_pin_dots.dart
> +  @override
nooooo

2024-12-05 06:49 UTC, YousefSalahKassem commented on lib/features/setup/presentation/widgets/custom_pin_dots.dart
> +        _text = widget.controller?.text ?? '';
NEVER!

2024-12-05 09:00 UTC, BakriIWNL commented on lib/core/components/bottomsheets/default_bottomsheet.dart
> +      const DropdownMenuItem(value: '0', child: Text("Bank")),
temp info
will localize

2024-12-05 09:02 UTC, BakriIWNL commented on lib/core/components/sheet_screen.dart
> +                10.verticalSpace,
alot of pages follow the format of (page with color number and one text) and a bottom sheet, so i kept this page as a common component for recycling, will make elements in it dynamically in a list when the time comes to it.

2024-12-05 09:03 UTC, BakriIWNL commented on lib/features/setup/presentation/widgets/custom_pin_dots.dart
> +        _text = widget.controller?.text ?? '';
will replace

2024-12-05 09:03 UTC, BakriIWNL commented on lib/features/setup/presentation/widgets/custom_pin_dots.dart
> +  @override
make it stateless?

2024-12-05 09:05 UTC, YousefSalahKassem commented on lib/features/setup/presentation/widgets/custom_pin_dots.dart
> +  @override
yeah and depend on state management

2024-12-05 09:06 UTC, YousefSalahKassem commented on lib/core/components/sheet_screen.dart
> +                10.verticalSpace,
try to make it as component not screen if you got what I mean

2024-12-05 09:07 UTC, BakriIWNL commented on lib/core/components/sheet_screen.dart
> +                10.verticalSpace,
will try

2024-12-10 07:54 UTC, YousefSalahKassem requested changes
GJ BAK BAK 
Check this comments

2024-12-10 07:54 UTC, YousefSalahKassem commented on lib/features/setup/presentation/cubit/setup/setup_cubit.dart
> +      emit(state.copyWith(states: GenericStates.initial));
why ? update then initial ?

2024-12-10 07:54 UTC, YousefSalahKassem commented on lib/features/setup/presentation/cubit/setup/setup_cubit.dart
> +      emit(state.copyWith(states: GenericStates.initial));
why ?

2024-12-10 08:35 UTC, BakriIWNL commented on lib/features/setup/presentation/cubit/setup/setup_cubit.dart
> +      emit(state.copyWith(states: GenericStates.initial));
will use success, thought it would be best interest to revert back to initial stable state after updating UI

2024-12-11 00:06 UTC, YousefSalahKassem approved these changes
GJ Bak Bak 
Proud of u <3

2024-12-11 00:06 UTC, YousefSalahKassem commented on lib/core/components/sheet_screen.dart
> +            AppLocalizations.of(context)!.newAccount,
can you try to search about how to add AppLocalizations in extension on context to make it easier like:
context.localizations.newAccount

2024-12-11 00:06 UTC, merged